services:
  app:
    build: .
    container_name: caja-cartas
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/app/uploads
